# name: Pipeline de CI/CD - Ticketon

# on:
#   push:
#     branches:
#       - main # Dispara sempre que houver merge ou push na main

# jobs:
#   build-and-push:
#     runs-on: ubuntu-latest

#     steps:
#       - name: 1. Checkout do Código
#         uses: actions/checkout@v4

#       - name: 2. Login no DockerHub
#         uses: docker/login-action@v3
#         with:
#           username: ${{ secrets.DOCKERHUB_USERNAME }}
#           password: ${{ secrets.DOCKERHUB_TOKEN }}

#       - name: 3. Construir e Enviar Imagem Docker
#         uses: docker/build-push-action@v5
#         with:
#           context: .
#           file: ./Dockerfile
#           target: runner # Usa o seu estágio leve de produção
#           push: true
#           # Usamos o HASH do commit como TAG da imagem. Isso é uma boa prática sênior 
#           # para rastrear exatamente qual código está rodando em produção.
#           tags: |
#             ${{ secrets.DOCKERHUB_USERNAME }}/ticketon-backend:${{ github.sha }}
#             ${{ secrets.DOCKERHUB_USERNAME }}/ticketon-backend:latest


name: Pipeline de CI/CD - Ticketon

on:
  push:
    branches:
      - main # Dispara sempre que houver merge ou push na main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: 1. Checkout do Código
        uses: actions/checkout@v4

      - name: 2. Login no DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: 3. Construir e Enviar Imagem Docker
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          target: runner # Usa o seu estágio leve de produção
          push: true
          # Usamos o HASH do commit como TAG da imagem. Isso é uma boa prática sênior 
          # para rastrear exatamente qual código está rodando em produção.
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/ticketon-backend:${{ github.sha }}
            ${{ secrets.DOCKERHUB_USERNAME }}/ticketon-backend:latest